### ISSUE TITLE
how to add transaction?

### ISSUE THREAD

**Issue by v8labx** [bxcodec/go-clean-arch#1]
i am new web developer, i don't know how to add transaction in the example。

sorry, my english is poor.

**Comment by bxcodec** [comment]
Hi @v8labx 
For transaction is depend on your DB. Is it your DB supported this.

For example MySql already support Transaction, you could read [here](http://go-database-sql.org/modifying.html)

For controlling the transaction, it must done in repository layer. 😄 

Thanks,
