### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by zczc521** [bxcodec/go-clean-arch#27]
db object in Repository , In userCase how do i use transaction?

**Comment by yanuarxnc** [comment]
I have same question.

**Comment by agungdwiprasetyo** [comment]
maybe you can use as I made here: https://github.com/agungdwiprasetyo/agungdpcms/blob/master/src/resume/usecase/usecase_impl.go#L77

**Comment by bxcodec** [comment]
Refer to this thread #11

**Comment by eddievim** [comment]
> maybe you can use as I made here: https://github.com/agungdwiprasetyo/agungdpcms/blob/master/src/resume/usecase/usecase_impl.go#L77

your code display usecases depend on Repo struct and it handle *gorm.DB, i think it not follow clean-arch rules?
