### ISSUE TITLE
more simple clean arch

### ISSUE THREAD

**Issue by alifpay** [bxcodec/go-clean-arch#48]
Hi 
I develop more simple clean arch

handlers: any transport layer http web api, grpc, graphql and etc.

app: Business layer

storage: Database and caches

services: external services

https://github.com/Abdukahhor/swe

what do you think ?

**Comment by aeharvlee** [comment]
I think it is not better than go-clean-arch.

Why the domain(=model) files are in app directory?
Imagine if you use about 15 domains in the project like,
"Dog, Cat, Cow, Horse, etc..."

If so, there is at least 15 domain files in app directory. 
It would be hard to read structure of project.

I think you should separate domain directory like clean-arch.

**Comment by bxcodec** [comment]
thanks for the reference, I will take a look later.
Let's have a proper discussion if needed. Feel free to ping me on Linkedin or Twitter or directly to my email. 

I'm closing this issue since it's not relevant to this repository.
