### ISSUE TITLE
How to implement method on domain

### ISSUE THREAD

**Issue by akmalhazim24** [bxcodec/go-clean-arch#54]
Hello,
May I know how to add hooks to our domain struct? Considering it is swappable, how can I add a hook to any of the domain struct for example using BeforeCreate (gorm hook).
Thank you

**Comment by bxcodec** [comment]
Hi! 

It's not domain responsibility to manage it. It should be on the repository layer. ORM is considered a repository layer. You can use databases with/without ORM in repository layer.

I'm closing this issue. Thanks!
