### ISSUE TITLE
How do we implement Bulk Update in this design pattern?

### ISSUE THREAD

**Issue by akmalhazim24** [bxcodec/go-clean-arch#55]
Hi,
May I know if there's a way for me to use any ORM update method without fetching the models first, right now from what I can see, the current pattern only allows the repository to update a single model. Is there any pattern that allows updating a single model and bulk update in one repository?
![image](https://user-images.githubusercontent.com/34267739/96712876-5da3ae00-13d2-11eb-897f-90d25f73a8ea.png)
Thank you

**Comment by bxcodec** [comment]
Hi!

Actually, you can just add a bulk update on your contract. The service/Usecase layer is built based on the business need/logic. So if your application business logic needs to have a bulk update, then you just need to define it on the contract. 
Also how to define the contract on the Service layer or Repository layer, I recommend reading more about SOLID principles. That's should help you a lot to define the contract functions.

I'm closing this issue as this for a personal question.
