### ISSUE TITLE
Question: Should we use a pointer as a return type of NewUsecase, NewRepository?

### ISSUE THREAD

**Issue by aeharvlee** [bxcodec/go-clean-arch#57]
In this repo, there are building functios like below(NewUsecase or NewRepository)
```go
type mysqlArticleRepository struct {
	Conn *sql.DB
}

// NewMysqlArticleRepository will create an object that represent the article.Repository interface
func NewMysqlArticleRepository(Conn *sql.DB) domain.ArticleRepository {
	return &mysqlArticleRepository{Conn}
}
```

As you can see, it returns address using `&mysqlArticleRepository` which of data type is a pointer.
So I think return type should be pointer `*domain.ArticleRepository` like below

```go
type mysqlArticleRepository struct {
	Conn *sql.DB
}

// NewMysqlArticleRepository will create an object that represent the article.Repository interface
func NewMysqlArticleRepository(Conn *sql.DB) *domain.ArticleRepository {
	return &mysqlArticleRepository{Conn}
}
```

I want to hear what you guys think about this.
Thanks for reading this issue. 😄

**Comment by ghostiam** [comment]
domain.ArticleRepository is interface, interface cannot be pointer.

**Comment by aeharvlee** [comment]
@ghostiam 
Thanks for your feedback. 👍

**Comment by frederikhors** [comment]
I think you can close this issue now.
