### ISSUE TITLE
How to handle multiple Repository transactions

### ISSUE THREAD

**Issue by OC0311** [bxcodec/go-clean-arch#59]
I have read your article and code to help me a lot, but I have a question, do not know how to solve, when a business needs multiple Repository cooperation, and they are a transaction, how to deal with such a situation? And this is the majority of cases, can you add similar examples in the code?

**Comment by mcwienczek** [comment]
isn't that a duplicate of https://github.com/bxcodec/go-clean-arch/issues/45 ?

**Comment by bxcodec** [comment]
duplicated by #45 
closing this, refer to #36(PR) for future transactions related
