### ISSUE TITLE
How do you reference ID's 

### ISSUE THREAD

**Issue by Taz17** [bxcodec/go-clean-arch#62]
In `domain/article.go` we have 

```go
type Article struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title" validate:"required"`
	Content   string    `json:"content" validate:"required"`
	Author    Author    `json:"author"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}
```

Here an `Author` attribute exists because an `Article` belongs to an `Author`

Going from that logic I attempted to add `ArticleStats` so I made the following changes:

in `domain/article.go`
```go
type Article struct {
	.
	.
	.
	ArticleStatistics ArticleStats `json:"article_statistics"`
}
```
and added

in `domain/articlestats.go`
```go
type ArticleStats struct {
	ID      int64   `json:"id"`
	Article Article `json:"article"`
	.
	.
	.
}
```

And I get  `illegal cycle in declaration of Article` + `illegal cycle in declaration of ArticleStats`

How is this solved?

**Comment by frederikhors** [comment]
@Taz17 I suggest you to read https://threedots.tech/post/ddd-lite-in-go-introduction/.

**Comment by Taz17** [comment]
Thank you, for everyone who is wondering what the answer would be its to reference a pointer to `Article` in `ArticleStats`

```go
type ArticleStats struct {
	ID       int64   `json:"id"`
	Article *Article `json:"article"`
	.
}
```
