### ISSUE TITLE
Question about manage 3rd service

### ISSUE THREAD

**Issue by thehaung** [bxcodec/go-clean-arch#72]
Hi, I consider about 3rd service in my repo, where i put this. Like i have a api call to another service in microservice system with REST/gRPC/Kafka/RabbitMQ, etc...

**Comment by masajip** [comment]
Hi, I think you just need to add a package inside your repo, such as `/repository/kafka` or `/repository/rabbitmq` and make a new type likes `kafkaAuthorRepo`, `rabbitmqAuthorRepo` inside of them

**Comment by thehaung** [comment]
Thanks @masajip for the answer
